### ISSUE TITLE
Response.__eq__: lenient type annotation

### ISSUE THREAD

**Issue by fsc-eriker** [mjcaley/aiospamc#288]
I had some sloppy code which basically tried

```
if aiospamc.response() != '':
```
This no longer works, and throws a fugly traceback:
```
 File "/var/task/aiospamc/responses.py", line 104, in __eq__
   self.version == other.version
```
I notice that aiospamc 0.7.0 [introduced an `__eq__` method for the `Response` class,](https://github.com/mjcaley/aiospamc/blob/development/aiospamc/responses.py#L102) but this method has a very lenient type annotation:

```
    def __eq__(self, other: Any) -> bool:
```
Shouldn't we require `other` to also be a `Response`, since it requires the object to have the same attributes? (The code below the statement from the traceback proceeds to check that `other` has attributes `other.headers`, `other.status_code`, `other.message`, and `other.body` which are also equal to the same attributes of `self`.)

**Comment by mjcaley** [comment]
Thanks for the comment!

I don't think there's anything that can be done about the type hint.  Since the `object` type defines it with that signature mypy ends up complaining.

I do agree about the stack trace though, that could probably be done better.  I'll probably implement a try-except to catch any `AttributeError` and return `False`.  That way if anyone does want to do duck typing with it, it won't fail if we otherwise would have done `isinstance`.
